name: 'Examples: Benchmark'

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018
        with:
          version: v1.41.1
          working-directory: examples/benchmark
          skip-go-installation: true

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1
    - name: Build
      working-directory: examples/benchmark
      run: go build ./...
    - name: Build Tests
      working-directory: examples/benchmark
      run: go test -exec=echo ./...
